filter_method: EKF #ESKF ,ESKFQK

data_path: /data/raw_data1 #数据使用  /data/raw_data; /data/raw_data1: raw_data是使用mid-accuracy IMU生成， raw_data1是使用low-accuracy IMU生成

earth:
  rotation_speed: 7.272205216e-05
  gravity: 9.79484197226504
  latitude: 32
  longtitude: 120

covariance:
  prior:
    posi: 1 # 1.0e-4
    vel: 1 # 1.0e-4
    ori: 1 # 1.0e-6
    gyro_delta: 1.0e-3  # 1.0e-6
    accel_delta: 1.0e-3 # 1.0e-6
  process: # Q
    gyro_delta: 1.0e-3
    accel_delta: 1.0e-4
  measurement:
    posi: 14

# quaternion kinematics for error state kalman filter
# 使用raw data
# qk_covariance:
#   prior:
#     posi: 1.0e-4
#     vel: 1.0e-4
#     ori: 1.0e-6
#     accel_delta: 1.0e-6
#     gyro_delta: 1.0e-6
#     g_delta: 1.0e-6
#   process: # Q
#     vel_delta: 1.0e-5
#     ori_delta: 1.0e-5
#     accel_delta: 1.0e-4
#     gyro_delta: 1.0e-5
#   measurement:
#     posi: 8

# 使用raw_data1,也可以用在raw_data上，只是精度会下降
qk_covariance:
  prior:
    posi: 1.0e-1
    vel: 1.0e-1
    ori: 1.0e-1
    accel_delta: 1.0e-1
    gyro_delta: 1.0e-1
    g_delta: 1.0e-1
  process: # Q
    vel_delta: 1.0
    ori_delta: 1.0
    accel_delta: 2.0
    gyro_delta: 2.0
  measurement:
    posi: 35